#!/bin/sh

# 判断是否是安全连接
if [ "${PROXY_SCHEME}" == "https" ] || [ "${PROXY_SCHEME}" == "HTTPS" ];then
  export SECURE="true"
else
  export SECURE="false"
fi


# 写入反向代理配置
if [ -z "${PROXY_DOMAIN}" ];then
  CONFIG_FILE=/config/shared/bitbucket.properties
  if [ ! -f "${CONFIG_FILE}" ]; then
    touch "${CONFIG_FILE}"
  fi

  property server.port 7990 ${CONFIG_FILE}
  property server.secure "${SECURE}" "${CONFIG_FILE}"
  property server.scheme "${PROXY_SCHEME}" "${CONFIG_FILE}"
  property server.proxy-port "${PROXY_PORT}" "${CONFIG_FILE}"
  property server.proxy-name "${PROXY_DOMAIN}" "${CONFIG_FILE}"
  property server.context-path "${CONTEXT_PATH}" "${CONFIG_FILE}"
fi


# 将主目录所有者改成系统创建的用户
chown -R "${USERNAME}":"${USERNAME}" "${BITBUCKET_HOME}"
